#!/bin/sh
DIRNAME="`dirname "$0"`"
cd "$DIRNAME"

# Try to increase the priority of the PRU access to the interconnect if devmemkm is installed
# See https://github.com/bigjosh/LEDscape#eliminating-the-white-flash-issue
# Note that this will return an error no matter what. LMK if you know how to check which error modprobe returned. 
modprobe devmemkm addr=0x44e10608 val=0x30

# Uncomment to ensure that SSH is running. It really sucks when you (or systemd) screw up it doesn't start. Since HDMI is disabled,
# it's REALLY important that SSHd be running, since you have no other easy option to connect.
# (sleep 30; /usr/bin/sshd -f /etc/ssh/sshd_config) &

modprobe uio_pruss
#./opc-server -P 7890 -s 48 -c 64
./opc-server --config /etc/ledscape-config.json
